// 200 lời chúc 20/10 (20 x 10) — mỗi lần tạo thiệp sẽ bốc ngẫu nhiên 1 câu
const wishes2010 = [
    // --- Nhóm gốc (chuyển thể từ bản 8/3) ---
    "Chúc bạn một ngày 20/10 thật trọn vẹn và nhiều niềm vui. Luôn giữ nụ cười tươi tắn trên môi nhé, vì bạn lúc mỉm cười là đẹp nhất đấy.",
    "Gửi đến bạn thân mến lời chúc 20/10 chân thành nhất. Mong bạn luôn tự tin, vững bước trên con đường mình chọn và mãi rạng rỡ như bây giờ.",
    "Nhân ngày Phụ nữ Việt Nam 20/10, tôi muốn chúc bạn luôn hạnh phúc và tràn đầy năng lượng. Làm bạn với bạn là một điều rất tuyệt vời trong cuộc sống của tôi.",
    "20/10 vui vẻ nhé. Cứ tiếp tục là một cô gái mạnh mẽ, thông minh và đầy khí chất như thế. Mọi điều tốt đẹp nhất sẽ đến với bạn thôi.",
    "Chúc bạn ngày Phụ nữ Việt Nam thật ấm áp bên những người thân yêu. Đừng quên dành chút thời gian chiều chuộng bản thân mình hơn nhé.",
    "Bạn luôn mang đến nguồn năng lượng rất tích cực. Nhân dịp 20/10, chúc bạn luôn giữ được sự lạc quan và yêu đời ấy trong mọi hoàn cảnh.",
    "Chúc bạn của tôi ngày lễ 20/10 nhận được thật nhiều điều tốt đẹp. Hãy luôn kiêu hãnh và tự hào về chính mình nha.",
    "Nhân ngày 20/10, chúc bạn gặt hái thêm nhiều thành công mới. Tôi tin với sự thông minh và nỗ lực của bạn, mọi mục tiêu đều sẽ nằm trong tầm tay.",
    "Dù cuộc sống bận rộn thế nào, ngày 20/10 này hãy bước chậm lại một chút để cảm nhận niềm vui. Chúc bạn luôn xinh đẹp và bình an.",
    "Chúc bạn một ngày 20/10 ngập tràn tiếng cười. Rất may mắn khi có một người bạn hiểu chuyện và duyên dáng như bạn để chia sẻ mọi điều.",
    "Tháng 10 thật dịu dàng, và bạn cũng vậy. Chúc bạn một ngày 20/10 ngập tràn yêu thương, sống trọn vẹn với đam mê và những gì mình yêu thích.",
    "Chúc mừng ngày Phụ nữ Việt Nam. Tôi luôn trân trọng sự quan tâm và tình bạn chân thành của bạn. Chúc bạn luôn hạnh phúc, vô lo và an nhiên nhé.",
    "20/10 chúc bạn rạng rỡ ngời ngời. Cứ lúc nào cũng vui vẻ thế này thì chẳng có muộn phiền nào dám làm khó cô gái mạnh mẽ như bạn đâu.",
    "Chúc ngày 20/10 của bạn thật rực rỡ và lấp lánh nụ cười. Mọi sự nỗ lực của bạn xứng đáng được đền đáp bằng những điều tuyệt vời nhất.",
    "Nhân ngày 20/10, chúc bạn của tôi mãi luôn xinh đẹp và tươi trẻ. Hãy cứ là chính mình – một phiên bản độc nhất và cực kỳ cuốn hút.",
    "Hôm nay là ngày của phái đẹp, và bạn xứng đáng là vì sao sáng nhất. Chúc bạn luôn giữ được nét đáng yêu và tấm lòng nhân hậu vốn có.",
    "20/10 vui nhé bạn. Mong rằng mỗi ngày của bạn đều yên bình, công việc hanh thông và con đường phía trước luôn trải đầy hoa thơm.",
    "Chúc bạn một ngày Phụ nữ Việt Nam thật rộn ràng. Tôi luôn khâm phục sự tinh tế và chu toàn của bạn trong vai trò một người đồng hành tuyệt vời.",
    "Gửi triệu điều tốt lành tới bạn nhân ngày 20/10. Đừng để bất cứ áp lực nào làm tắt đi nụ cười tỏa nắng trên khuôn mặt bạn nhé.",
    "Chúc bạn 20/10 hạnh phúc viên mãn. Những nét duyên dáng, thông minh và sự tốt bụng của bạn là điều khiến mọi người luôn quý mến.",
    "Nhân ngày 20/10, chúc bạn có một ngày đầy ắp hạnh phúc và niềm vui. Cảm ơn bạn vì đã luôn chia sẻ và lắng nghe mọi chuyện với mọi người.",
    "Chào ngày 20/10. Chúc bạn lúc nào cũng được tỏa sáng rạng rỡ. Cứ bước đi tự tin, vì bạn rất rạng rỡ.",
    "Phụ nữ quyến rũ nhất khi họ tự tin, và bạn chính là minh chứng cho điều đó. Chúc ngày 20/10 của bạn thật lộng lẫy và đáng trân trọng.",
    "Gửi bạn lời chúc 20/10 đầy mến thương. Bạn là một mảnh ghép rất ý nghĩa trong cuộc sống của những người xung quanh, mãi nở nụ cười nhé.",

    // --- Ấm áp & quan tâm ---
    "Ngày 20/10 này, chúc bạn được nghỉ ngơi đúng nghĩa: ngủ thật ngon, ăn thật no và cười thật nhiều. Bạn đã vất vả nhiều rồi, hôm nay cứ thong thả thôi.",
    "Cảm ơn bạn vì luôn là người lắng nghe kiên nhẫn nhất. Nhân ngày Phụ nữ Việt Nam, chúc bạn cũng luôn có người lắng nghe và thấu hiểu mình như thế.",
    "Chúc bạn một ngày 20/10 nhẹ nhàng như gió thu tháng Mười. Mong mọi lo toan tạm gác lại, chỉ còn niềm vui và những điều dễ thương ở lại.",
    "Ở bên bạn, mọi chuyện dường như dễ dàng hơn hẳn. Chúc bạn ngày 20/10 thật ngọt ngào và một năm thật nhiều may mắn.",
    "Bạn không cần phải hoàn hảo, chỉ cần là bạn thôi đã đủ tuyệt rồi. Chúc bạn một ngày 20/10 thật thoải mái và đáng nhớ.",
    "Chúc cô gái chăm chỉ nhất mà tôi biết một ngày 20/10 thật xứng đáng. Hôm nay hãy để mọi người chiều chuộng bạn một chút nhé.",
    "Mỗi lần gặp bạn là một lần thấy vui lây. Nhân ngày 20/10, chúc bạn luôn giữ được nguồn năng lượng tươi sáng ấy.",
    "Chúc bạn 20/10 an yên, sức khỏe dồi dào và lúc nào cũng có lý do để mỉm cười. Những điều tốt đẹp nhất xin dành cho bạn.",
    "Mong rằng tháng Mười này mang đến cho bạn thật nhiều tin vui. Chúc bạn một ngày Phụ nữ Việt Nam rạng ngời và hạnh phúc.",
    "Bạn là kiểu người khiến người khác thấy ấm lòng chỉ bằng một câu hỏi thăm. Chúc bạn 20/10 nhận lại thật nhiều sự quan tâm như vậy.",
    "Chúc bạn ngày 20/10 vui hết cỡ, xinh hết nấc và hạnh phúc không giới hạn. Cứ tự tin tỏa sáng theo cách riêng của mình nhé.",
    "Có những người chỉ cần xuất hiện là đủ làm ngày hôm đó đẹp hơn, và bạn là một người như thế. Chúc bạn 20/10 thật trọn vẹn.",
    "Nhân ngày 20/10, chúc bạn luôn đủ mạnh mẽ để vượt qua thử thách và đủ dịu dàng để yêu thương bản thân mình.",
    "Gửi bạn một bó hoa tưởng tượng thật to và một lời chúc thật lòng: mong bạn luôn bình an, vui vẻ và được yêu thương.",
    "Chúc bạn có một ngày 20/10 mà khi nhìn lại sẽ thấy thật đáng nhớ. Bạn xứng đáng với tất cả những điều tuyệt vời ấy.",
    "Cảm ơn bạn vì đã luôn cố gắng hết mình trong mọi việc. Ngày 20/10 này, chúc bạn được tưởng thưởng bằng thật nhiều niềm vui.",
    "Chúc bạn luôn giữ được ánh mắt sáng và nụ cười hiền như bây giờ. Một ngày Phụ nữ Việt Nam thật ấm áp và ngọt ngào nhé.",
    "Mong mỗi sáng thức dậy bạn đều thấy lòng nhẹ tênh và tràn đầy hứng khởi. Chúc bạn 20/10 thật vui và thật nhiều may mắn.",
    "Bạn đã làm rất tốt rồi, thật đấy. Nhân ngày 20/10, chúc bạn biết rằng mình luôn được trân trọng và ghi nhận.",
    "Chúc bạn một ngày 20/10 thật rực rỡ, nơi mọi điều nhỏ bé cũng trở nên đáng yêu và mọi nỗ lực đều được đền đáp xứng đáng.",
    "Chúc người bạn tâm lý của tôi ngày 20/10 thật hạnh phúc. Cảm ơn bạn vì luôn biết cách khiến mọi người cảm thấy dễ chịu.",
    "Hôm nay là ngày của bạn, nên cứ thoải mái làm điều mình thích nhé. Chúc bạn 20/10 vui vẻ, an nhiên và tràn ngập tiếng cười.",
    "Mong bạn luôn có đủ thời gian cho những điều mình yêu, đủ sức khỏe cho những ước mơ mình theo đuổi. Chúc mừng ngày 20/10.",
    "Bạn dịu dàng nhưng không yếu đuối, mạnh mẽ nhưng vẫn rất tinh tế. Chúc bạn một ngày Phụ nữ Việt Nam thật tuyệt vời.",
    "Chúc bạn 20/10 được nhận nhiều hoa, nhiều quà và quan trọng nhất là nhiều yêu thương chân thành từ những người xung quanh.",
    "Thế giới sẽ kém vui đi nhiều nếu thiếu nụ cười của bạn. Chúc bạn ngày 20/10 luôn rạng rỡ và lạc quan như thế.",
    "Nhân ngày 20/10, chúc bạn có một trái tim bình yên, một tâm hồn vui tươi và những người bạn luôn sẵn sàng ở bên.",
    "Chúc bạn tháng Mười thật nhiều điều mới mẻ, công việc thuận lợi và những ngày bình thường cũng hóa thành ngày đặc biệt.",
    "Bạn luôn biết cách biến những điều giản dị thành điều đáng nhớ. Chúc bạn một ngày 20/10 thật ý nghĩa và ngập tràn niềm vui.",
    "Gửi đến bạn lời chúc 20/10 từ tận đáy lòng: mong bạn luôn khỏe mạnh, luôn được yêu thương và luôn là phiên bản hạnh phúc nhất của mình.",

    // --- Yêu bản thân & nghỉ ngơi ---
    "Ngày 20/10, hãy tự thưởng cho mình một ly trà sữa, một bộ phim hay hoặc một giấc ngủ trưa thật dài. Bạn xứng đáng mà.",
    "Chúc bạn biết yêu bản thân nhiều hơn một chút mỗi ngày. Ngày 20/10 này, hãy dành vài phút để tự khen mình nhé.",
    "Đừng quên rằng bạn cũng cần được chăm sóc như cách bạn vẫn chăm sóc mọi người. Chúc bạn một ngày 20/10 thật thư thái.",
    "Chúc bạn 20/10 bớt lo âu, thêm thảnh thơi, bớt deadline, thêm niềm vui. Mọi chuyện rồi sẽ ổn cả thôi.",
    "Mong bạn luôn cho phép mình được nghỉ ngơi khi mệt và được vui vẻ khi muốn. Chúc mừng ngày Phụ nữ Việt Nam 20/10.",
    "Hôm nay không cần cố gắng gì cả, chỉ cần vui là đủ. Chúc bạn một ngày 20/10 thật nhẹ nhàng và đáng yêu.",
    "Chúc bạn luôn giữ được sự cân bằng giữa công việc và cuộc sống, giữa ước mơ và bình yên. Ngày 20/10 thật vui nhé.",
    "Nhân ngày 20/10, chúc bạn có thật nhiều khoảnh khắc chỉ dành riêng cho mình, để nghỉ ngơi, mơ mộng và nạp lại năng lượng.",
    "Chúc bạn có một ngày 20/10 trọn vẹn từ bữa sáng ngon miệng đến giấc ngủ ngon lành. Mọi điều dễ chịu nhất đều dành cho bạn.",
    "Bạn đã mạnh mẽ đủ lâu rồi, hôm nay hãy cho phép mình được nhõng nhẽo một chút. Chúc bạn 20/10 thật vui và ấm áp.",

    // --- Công việc & thành công ---
    "Chúc bạn 20/10 công việc suôn sẻ, sếp thương đồng nghiệp quý và mọi kế hoạch đều diễn ra đúng như mong đợi.",
    "Sự tận tâm của bạn là nguồn cảm hứng cho rất nhiều người. Nhân ngày 20/10, chúc bạn ngày càng thành công và hạnh phúc.",
    "Chúc bạn luôn tự tin vào năng lực của mình và dám theo đuổi những điều lớn lao. Ngày Phụ nữ Việt Nam thật rực rỡ nhé.",
    "Mong mọi dự định của bạn trong năm nay đều thành hiện thực. Chúc bạn một ngày 20/10 thật vui và tràn đầy cảm hứng.",
    "Làm việc cùng bạn luôn là một niềm vui. Chúc bạn 20/10 thật nhiều sức khỏe, thật nhiều niềm vui và thật nhiều thành công.",
    "Chúc bạn ngày 20/10 thăng hoa trong công việc và bình yên trong cuộc sống. Những gì bạn gieo hôm nay sẽ sớm nở hoa thôi.",
    "Bạn giỏi giang mà vẫn khiêm tốn, bận rộn mà vẫn chu đáo. Chúc bạn một ngày 20/10 thật xứng đáng với tất cả những điều ấy.",
    "Nhân ngày 20/10, chúc bạn luôn giữ được ngọn lửa đam mê và sự kiên trì để chinh phục mọi mục tiêu phía trước.",
    "Chúc bạn có một năm thật bứt phá, học được nhiều điều hay và gặp được nhiều người tốt. Chúc mừng ngày 20/10.",
    "Mỗi thành công của bạn đều xứng đáng được tự hào. Chúc bạn 20/10 thật rạng rỡ và tiếp tục tiến xa hơn nữa nhé.",

    // --- Xinh đẹp & duyên dáng ---
    "Chúc bạn 20/10 lúc nào cũng xinh, chụp ảnh góc nào cũng đẹp và soi gương lần nào cũng thấy yêu mình hơn.",
    "Vẻ đẹp của bạn không chỉ ở nụ cười mà còn ở tấm lòng. Nhân ngày 20/10, chúc bạn luôn tỏa sáng từ bên trong.",
    "Chúc bạn mãi giữ được nét duyên rất riêng khiến ai gặp cũng thấy dễ mến. Một ngày Phụ nữ Việt Nam thật ngọt ngào nhé.",
    "Bạn đẹp nhất khi được là chính mình. Chúc bạn 20/10 luôn tự tin, rạng rỡ và chẳng ngại thể hiện bản thân.",
    "Chúc bạn ngày 20/10 trẻ trung như tuổi đôi mươi và rạng ngời như nắng sớm. Năm tháng chỉ làm bạn thêm duyên dáng mà thôi.",
    "Mong bạn luôn thấy mình xinh đẹp, không chỉ hôm nay mà mọi ngày trong năm. Chúc mừng ngày 20/10 thật vui nhé.",
    "Nụ cười của bạn có sức lan tỏa ghê lắm đấy. Chúc bạn 20/10 cười thật nhiều để cả thế giới cùng vui theo.",
    "Chúc bạn một ngày 20/10 lung linh như chính con người bạn: tươi tắn, ấm áp và luôn khiến người khác muốn ở gần.",
    "Thanh lịch, thông minh và tốt bụng, bạn có đủ cả. Chúc bạn ngày Phụ nữ Việt Nam thật hạnh phúc và đáng nhớ.",
    "Chúc bạn 20/10 rạng rỡ như đóa hoa đẹp nhất trong vườn, luôn tươi mới và tỏa hương theo cách riêng của mình.",

    // --- Tình bạn ---
    "Có bạn đồng hành, những ngày bình thường cũng trở nên thú vị hơn nhiều. Chúc bạn một ngày 20/10 thật vui và thật ý nghĩa.",
    "Cảm ơn bạn vì những lần sẻ chia, những câu chuyện không đầu không cuối và những tràng cười giòn tan. Chúc mừng 20/10 nhé.",
    "Tình bạn của chúng ta là món quà tôi luôn trân trọng. Nhân ngày 20/10, chúc bạn luôn hạnh phúc và bình an.",
    "Chúc bạn của tôi 20/10 vui như Tết, cười không ngớt và nhận quà mỏi tay. Mãi là cô bạn đáng yêu như thế nhé.",
    "Dù bận rộn đến đâu, mong chúng ta vẫn luôn dành cho nhau những lời hỏi thăm. Chúc bạn một ngày 20/10 thật ấm áp.",
    "Bạn là người bạn mà ai cũng mong có được. Chúc bạn ngày 20/10 nhận lại thật nhiều yêu thương như những gì bạn đã cho đi.",
    "Cảm ơn bạn vì đã luôn ở đó mỗi khi tôi cần. Ngày 20/10 này, chúc bạn mọi điều tốt lành và một trái tim luôn vui vẻ.",
    "Chúc bạn 20/10 thật nhiều niềm vui. Những kỷ niệm cùng bạn luôn là phần đẹp nhất trong ký ức của tôi.",
    "Mong tình bạn này cứ bền lâu như thế, giản dị mà chân thành. Chúc bạn một ngày Phụ nữ Việt Nam thật hạnh phúc.",
    "Có một người bạn hiểu mình như bạn là điều may mắn lắm. Chúc bạn ngày 20/10 thật trọn vẹn và an yên.",

    // --- Gia đình & mái ấm ---
    "Chúc bạn ngày 20/10 bên gia đình thật đầm ấm. Mong những người bạn thương luôn khỏe mạnh và bình an bên bạn.",
    "Bạn luôn chu toàn cho mọi người xung quanh. Nhân ngày 20/10, chúc bạn cũng được yêu thương và chăm sóc thật nhiều.",
    "Chúc bạn một ngày 20/10 có bữa cơm thật ngon, có người thân bên cạnh và có thật nhiều tiếng cười trong nhà.",
    "Sự ân cần của bạn là điều khiến ai cũng thấy ấm lòng. Chúc bạn ngày Phụ nữ Việt Nam thật hạnh phúc và đủ đầy.",
    "Mong ngôi nhà của bạn luôn tràn ngập yêu thương và tiếng cười. Chúc bạn một ngày 20/10 thật ấm áp và ý nghĩa.",
    "Chúc bạn 20/10 vừa là chính mình rạng rỡ, vừa là chỗ dựa vững vàng cho những người thân yêu. Bạn thật tuyệt vời.",
    "Đằng sau mỗi sự bình yên của gia đình luôn có bàn tay chăm chút của người phụ nữ. Chúc bạn một ngày 20/10 thật trọn vẹn.",
    "Chúc bạn có một ngày 20/10 được cả nhà cưng chiều, được nghỉ tay khỏi việc bếp núc và chỉ việc tận hưởng niềm vui.",
    "Bạn là người luôn biết vun vén và giữ lửa cho mọi người. Chúc bạn ngày 20/10 thật nhiều sức khỏe và hạnh phúc.",
    "Mong bạn luôn có một mái ấm để trở về và những người thương để sẻ chia. Chúc mừng ngày Phụ nữ Việt Nam 20/10.",

    // --- Mùa thu tháng Mười ---
    "Tháng Mười mang theo gió heo may và những điều dịu dàng nhất. Chúc bạn một ngày 20/10 thật bình yên và thơ mộng.",
    "Chúc bạn 20/10 ngọt ngào như hương hoa sữa cuối thu, dịu dàng như nắng chiều tháng Mười. Thật nhiều niềm vui nhé.",
    "Thu về trời trong xanh, mong lòng bạn cũng nhẹ nhàng như thế. Chúc bạn một ngày Phụ nữ Việt Nam thật hạnh phúc.",
    "Chúc bạn một mùa thu đẹp với những buổi sáng se lạnh, ly cà phê ấm và những người thương bên cạnh. Chúc mừng 20/10.",
    "Giữa tiết trời tháng Mười dịu mát, gửi đến bạn lời chúc 20/10 thật ấm áp: luôn vui, luôn khỏe và luôn được yêu thương.",
    "Lá vàng rơi nhẹ, gió thu khẽ thổi, và hôm nay là ngày của bạn. Chúc bạn 20/10 thật lãng mạn và đáng nhớ.",
    "Mong những ngày thu của bạn luôn trong trẻo như bầu trời tháng Mười. Chúc bạn một ngày 20/10 thật vui và an nhiên.",
    "Chúc bạn 20/10 tươi tắn như cúc họa mi đầu mùa, nhỏ nhắn mà kiên cường, giản dị mà vẫn khiến người ta thương mến.",
    "Mùa thu đẹp nhất là khi có những người đáng yêu như bạn. Chúc bạn ngày 20/10 ngập tràn niềm vui và hạnh phúc.",
    "Tháng Mười về, gửi bạn chút nắng vàng và cả một trời thương mến. Chúc bạn một ngày Phụ nữ Việt Nam thật ngọt ngào.",

    // --- Mạnh mẽ & kiên cường ---
    "Bạn đã đi qua nhiều ngày khó khăn mà vẫn giữ được nụ cười, điều đó thật đáng ngưỡng mộ. Chúc bạn 20/10 thật bình an.",
    "Chúc bạn luôn vững vàng trước sóng gió và nhẹ nhàng trước những điều không như ý. Ngày 20/10 thật ấm áp nhé.",
    "Sự kiên cường của bạn luôn khiến tôi nể phục. Nhân ngày Phụ nữ Việt Nam, chúc bạn mọi điều thuận lợi và hạnh phúc.",
    "Không phải ai cũng mạnh mẽ được như bạn. Chúc bạn 20/10 thật vui và biết rằng mình không bao giờ phải cố gắng một mình.",
    "Chúc bạn có đủ dũng khí để bắt đầu, đủ kiên nhẫn để đi tiếp và đủ niềm tin để chạm tới ước mơ. Chúc mừng 20/10.",
    "Mỗi vấp ngã chỉ khiến bạn trưởng thành và rạng rỡ hơn. Chúc bạn một ngày 20/10 thật tự hào về hành trình của mình.",
    "Bạn mạnh mẽ theo cách rất riêng: lặng lẽ, bền bỉ và đầy bản lĩnh. Chúc bạn ngày 20/10 luôn được tiếp thêm sức mạnh.",
    "Chúc bạn 20/10 luôn tin rằng mình làm được, vì thật sự bạn làm được nhiều điều hơn bạn nghĩ đấy.",
    "Mong những điều khó khăn sẽ sớm qua đi, chỉ còn lại bình yên và niềm vui. Chúc bạn một ngày Phụ nữ Việt Nam thật ấm áp.",
    "Chúc bạn luôn giữ được sự kiên định trong lòng và sự dịu dàng trong ánh mắt. Ngày 20/10 thật tuyệt vời nhé.",

    // --- Vui nhộn & dễ thương ---
    "Chúc bạn 20/10 ăn hoài không mập, tiêu hoài không hết tiền và lúc nào cũng có người rủ đi chơi.",
    "Hôm nay bạn được quyền làm nữ hoàng nhé. Chúc bạn 20/10 vui hết mình, quà nhận không xuể và cười tít cả mắt.",
    "Chúc bạn ngày 20/10 ví luôn dày, da luôn đẹp, tóc luôn suôn và tâm trạng lúc nào cũng tươi như hoa.",
    "Chúc bạn 20/10 thật nhiều quà, thật nhiều hoa và thật nhiều tin nhắn chúc mừng đến mức đọc không kịp.",
    "Mong ngày 20/10 của bạn không có deadline, không có kẹt xe và chỉ toàn những điều dễ thương thôi nhé.",
    "Chúc bạn 20/10 luôn được nhường phần ngon nhất, chỗ ngồi đẹp nhất và nhận những lời khen chân thành nhất.",
    "Hôm nay cứ thoải mái ăn món mình thích, mua món mình mê. Chúc bạn một ngày 20/10 thật chill và thật vui.",
    "Chúc bạn 20/10 mọi chuyện đều thuận buồm xuôi gió, tiền vào như nước, còn buồn phiền thì bay đi mất tiêu.",
    "Chúc bạn có một ngày 20/10 đầy bất ngờ dễ thương, từ ly cà phê được mời đến những lời khen không báo trước.",
    "Nếu hôm nay có ai làm bạn buồn, cứ bảo tôi nhé. Chúc bạn 20/10 chỉ toàn niềm vui và nụ cười thôi.",

    // --- Biết ơn ---
    "Cảm ơn bạn vì đã mang đến cho mọi người thật nhiều điều tốt đẹp. Ngày 20/10, chúc bạn nhận lại gấp bội yêu thương.",
    "Những việc tử tế bạn làm, dù nhỏ, đều được mọi người ghi nhớ. Chúc bạn một ngày Phụ nữ Việt Nam thật hạnh phúc.",
    "Cảm ơn bạn vì sự tận tình và chu đáo trong từng việc nhỏ. Chúc bạn 20/10 thật nhiều sức khỏe và niềm vui.",
    "Có bạn, mọi thứ trở nên gọn gàng và ấm áp hơn hẳn. Nhân ngày 20/10, gửi bạn lời cảm ơn và lời chúc thật lòng.",
    "Cảm ơn bạn vì luôn kiên nhẫn, luôn bao dung và luôn sẵn lòng giúp đỡ. Chúc bạn một ngày 20/10 thật trọn vẹn.",
    "Sự hiện diện của bạn đã làm cho tập thể này thêm gắn kết và vui vẻ. Chúc bạn 20/10 rạng rỡ và hạnh phúc.",
    "Cảm ơn bạn vì đã truyền cảm hứng cho tôi theo những cách mà có lẽ bạn không hề biết. Chúc mừng ngày 20/10 nhé.",
    "Có những điều bạn làm mà chẳng cần ai nhắc, chẳng cần ai khen. Hôm nay tôi muốn nói: cảm ơn bạn và chúc bạn 20/10 thật vui.",
    "Cảm ơn bạn vì những lời động viên đúng lúc. Chúc bạn ngày Phụ nữ Việt Nam luôn được tiếp thêm năng lượng và niềm vui.",
    "Mọi người quý bạn không phải vì bạn hoàn hảo, mà vì bạn chân thành. Chúc bạn 20/10 luôn giữ được tấm lòng ấy.",

    // --- Ước mơ & tương lai ---
    "Chúc bạn 20/10 dám mơ lớn và dám bước những bước đầu tiên. Tương lai rực rỡ đang chờ bạn ở phía trước.",
    "Mong mọi điều ước của bạn năm nay đều có cơ hội thành hiện thực. Chúc bạn một ngày 20/10 thật nhiều hy vọng.",
    "Chúc bạn luôn giữ được sự tò mò và háo hức với cuộc sống. Mỗi ngày mới đều là một trang đẹp để bạn viết tiếp. Chúc mừng 20/10.",
    "Nhân ngày 20/10, chúc bạn tìm thấy niềm vui trong những điều mình đang làm và sự bình yên trên con đường mình đã chọn.",
    "Chúc bạn có thật nhiều chuyến đi đẹp, những trải nghiệm mới và những kỷ niệm khó quên. Ngày 20/10 thật vui nhé.",
    "Mong bạn luôn có đủ tự do để là chính mình và đủ yêu thương để không bao giờ thấy cô đơn. Chúc mừng 20/10.",
    "Chúc bạn một tương lai sáng như ánh mắt bạn mỗi khi kể về ước mơ của mình. Ngày Phụ nữ Việt Nam thật hạnh phúc.",
    "Mỗi ngày trôi qua, mong bạn lại tiến gần hơn một chút tới phiên bản mà mình mong muốn. Chúc bạn 20/10 rạng rỡ.",
    "Chúc bạn luôn có cơ hội học hỏi, trưởng thành và tỏa sáng. Ngày 20/10, mọi cánh cửa tốt đẹp đều đang rộng mở chào đón bạn.",
    "Nhân ngày 20/10, chúc bạn luôn tin rằng những điều tốt đẹp nhất vẫn còn ở phía trước và đang đến gần.",

    // --- Giản dị & chân thành ---
    "Chúc bạn 20/10 vui vẻ, khỏe mạnh và luôn được bao quanh bởi những người thật lòng thương mến mình.",
    "Một lời chúc giản dị cho một người đặc biệt: mong bạn luôn hạnh phúc. Chúc mừng ngày Phụ nữ Việt Nam 20/10.",
    "Chúc bạn có một ngày 20/10 đẹp như một bức tranh, từ sáng đến tối đều có màu của niềm vui.",
    "Mong bạn luôn được bình yên giữa những bộn bề, luôn tìm thấy niềm vui trong những điều nhỏ bé. Chúc mừng 20/10.",
    "Chúc bạn 20/10 thật nhiều năng lượng tích cực, để mỗi ngày đều là một ngày đáng sống và đáng nhớ.",
    "Hôm nay, chúc bạn được là người hạnh phúc nhất. Ngày mai và cả những ngày sau nữa, cũng mong như vậy. Chúc mừng 20/10.",
    "Chúc bạn một ngày 20/10 thật trong trẻo, không muộn phiền, không vướng bận, chỉ có niềm vui và sự bình an.",
    "Mong bạn luôn được đối xử dịu dàng, cả bởi người khác và bởi chính mình. Chúc bạn ngày 20/10 thật ấm áp.",
    "Chúc bạn 20/10 luôn có người hỏi han khi mệt, có người sẻ chia khi buồn và có người cùng vui khi hạnh phúc.",
    "Gửi bạn ngàn lời chúc tốt lành nhân ngày 20/10: sức khỏe dồi dào, công việc hanh thông và tình cảm viên mãn.",

    // --- Tấm lòng & phẩm chất ---
    "Tấm lòng tốt của bạn là thứ khiến bạn đẹp nhất. Chúc bạn một ngày 20/10 nhận lại thật nhiều điều tử tế.",
    "Bạn luôn nhìn thấy điều tốt ở người khác, nên mong mọi người cũng luôn nhìn thấy điều tuyệt vời ở bạn. Chúc mừng 20/10.",
    "Chúc bạn giữ mãi sự hồn nhiên và lòng tốt ấy, dù cuộc sống có đổi thay thế nào. Ngày Phụ nữ Việt Nam thật vui nhé.",
    "Sự chân thành của bạn là điều hiếm có. Chúc bạn 20/10 luôn gặp được những người xứng đáng với tấm lòng ấy.",
    "Bạn tinh tế đến mức luôn nhận ra khi ai đó cần được quan tâm. Chúc bạn ngày 20/10 cũng được quan tâm thật nhiều.",
    "Chúc bạn 20/10 luôn bình tĩnh, sáng suốt và bao dung như cách bạn vẫn đối xử với mọi người xung quanh.",
    "Ở bạn có sự ấm áp khiến người khác muốn tin tưởng và gắn bó. Chúc bạn một ngày 20/10 thật hạnh phúc.",
    "Chúc bạn luôn giữ được sự khiêm nhường và lòng biết ơn, hai điều khiến bạn trở nên thật đáng quý. Chúc mừng 20/10.",
    "Bạn luôn khiến mọi người cảm thấy mình được tôn trọng và lắng nghe. Ngày 20/10, chúc bạn cũng luôn được đối xử như thế.",
    "Chúc bạn 20/10 tràn ngập niềm vui, vì một người tốt bụng như bạn xứng đáng với tất cả những điều tốt đẹp nhất.",

    // --- Tự hào phụ nữ Việt ---
    "Nhân ngày Phụ nữ Việt Nam, chúc bạn luôn tự hào về sự đảm đang, khéo léo và bản lĩnh của mình.",
    "Chúc bạn 20/10 mang trọn vẻ đẹp của người phụ nữ Việt: dịu dàng, kiên trung và luôn ấm áp tình người.",
    "Giữa nhịp sống hiện đại, bạn vẫn giữ được nét đẹp truyền thống thật đáng quý. Chúc bạn một ngày 20/10 thật rạng ngời.",
    "Chúc bạn ngày Phụ nữ Việt Nam thật ý nghĩa, như một lời ghi nhận cho tất cả những hy sinh thầm lặng mà bạn đã làm.",
    "Duyên dáng như tà áo dài, bền bỉ như cây lúa, đó chính là bạn. Chúc bạn 20/10 thật hạnh phúc và an vui.",
    "Chúc bạn luôn là người phụ nữ hiện đại tự tin mà vẫn giữ trọn nét dịu hiền. Ngày 20/10 thật trọn vẹn nhé.",
    "Hôm nay cả nước tôn vinh phụ nữ Việt Nam, và tôi muốn dành lời chúc đặc biệt nhất cho bạn: luôn hạnh phúc nhé.",
    "Chúc bạn 20/10 vững vàng trong sự nghiệp, ấm áp trong gia đình và rạng rỡ trong chính cuộc sống của mình.",
    "Người phụ nữ Việt luôn có một sức mạnh rất đặc biệt, và bạn là minh chứng rõ nhất. Chúc bạn một ngày 20/10 thật tuyệt.",
    "Nhân ngày 20/10, chúc bạn luôn được tôn trọng, được yêu thương và được sống đúng với những gì mình mong muốn.",

    // --- Ngày đặc biệt của bạn ---
    "Chúc bạn 20/10 có một buổi sáng thật đẹp để bắt đầu, một buổi chiều thật vui để tận hưởng và một buổi tối thật ấm để khép lại.",
    "Mong rằng hôm nay bạn sẽ nhận được ít nhất một điều khiến bạn mỉm cười thật lâu. Chúc mừng ngày 20/10 nhé.",
    "Chúc bạn ngày 20/10 tràn đầy cảm hứng, để từng việc nhỏ cũng trở nên thú vị và đầy ý nghĩa.",
    "Bạn là điều may mắn mà cuộc sống đã mang đến cho những người xung quanh. Chúc bạn một ngày Phụ nữ Việt Nam thật vui.",
    "Chúc bạn 20/10 luôn có người nhớ đến, có người chờ đợi và có người sẵn sàng cùng bạn đi qua mọi chặng đường.",
    "Mong mỗi ngày của bạn đều có một chút ngọt ngào, một chút bất ngờ và thật nhiều niềm vui. Chúc mừng 20/10.",
    "Chúc bạn một ngày 20/10 thật tươi sáng, như cách bạn vẫn làm bừng sáng không khí mỗi khi xuất hiện.",
    "Chúc bạn có thêm nhiều lý do để yêu đời, nhiều người để thương và nhiều điều để biết ơn. Ngày 20/10 hạnh phúc nhé.",
    "Hôm nay hãy để những lời chúc phúc bao bọc lấy bạn. Chúc bạn 20/10 vui tươi, ấm áp và tràn đầy yêu thương.",
    "Chúc bạn 20/10 luôn giữ được trái tim ấm, cái đầu tỉnh và một nụ cười chẳng bao giờ tắt.",

    // --- Lời chúc trọn vẹn ---
    "Mong rằng những điều bạn chờ đợi bấy lâu sẽ sớm gõ cửa. Chúc bạn một ngày 20/10 thật nhiều niềm vui và hy vọng.",
    "Chúc bạn 20/10 hạnh phúc theo cách bạn muốn, thành công theo cách bạn chọn và bình yên theo cách bạn cần.",
    "Bạn xứng đáng được nâng niu như một món quà quý. Chúc bạn ngày Phụ nữ Việt Nam thật ngọt ngào và đáng nhớ.",
    "Chúc bạn một ngày 20/10 mà mọi lời chúc đều thành sự thật và mọi nụ cười đều xuất phát từ trái tim.",
    "Cuộc sống đẹp hơn vì có những người như bạn. Chúc bạn 20/10 luôn rạng ngời, khỏe mạnh và hạnh phúc.",
    "Gửi bạn một lời chúc giản dị mà chân thành: mong bạn mãi là chính mình, mãi vui và mãi được yêu thương. Chúc mừng 20/10."
];
